set -exou

mkdir -p "${PREFIX}/include/speech_tools"
mkdir -p "${PREFIX}/include/speech_tools/unix"
mkdir -p "${PREFIX}/include/speech_tools/base_class"
mkdir -p "${PREFIX}/include/speech_tools/instantiate"
mkdir -p "${PREFIX}/include/speech_tools/ling_class"
mkdir -p "${PREFIX}/include/speech_tools/rxp"
mkdir -p "${PREFIX}/include/speech_tools/sigpr"
mkdir -p "${PREFIX}/lib"
mkdir -p "${PREFIX}/lib/speech_tools"
mkdir -p "${PREFIX}/lib/speech_tools/lib/siod"

cp include/*.h "${PREFIX}/include/speech_tools/"
cp include/unix/*.h "${PREFIX}/include/speech_tools/unix/"
cp base_class/*.cc "${PREFIX}/include/speech_tools/base_class/"
cp base_class/*.h "${PREFIX}/include/speech_tools/"
cp include/instantiate/*.h "${PREFIX}/include/speech_tools/instantiate/"
cp include/ling_class/*.h "${PREFIX}/include/speech_tools/ling_class/"
cp include/rxp/*.h "${PREFIX}/include/speech_tools/rxp/"
cp include/sigpr/*.h "${PREFIX}/include/speech_tools/sigpr/"
cp lib/lib*.a "${PREFIX}/lib/"
cp -P lib/lib*.so "${PREFIX}/lib/"
cp -a config "${PREFIX}/lib/speech_tools/"
cp make.include "${PREFIX}/lib/speech_tools/"
cp lib/siod/*.scm "${PREFIX}/lib/speech_tools/lib/siod/"
